# Versions
# Virtual OS: Debian buster 10.11.1
# Docker version 18.09.1, build 4c52b90 
# docker-compose version 1.29.2, build 5becea4c

# Local OS: Mac OS X
# Docker version 20.10.12, build e91ed57
# docker-compose version 1.29.2, build 5becea4c

# Compose file format 3.7 - Docker engine 18.06.0+

# References

# version: docker-compose.yml version
# services:
#   service name: It's the name of service
#     build:
#       context: Dockerfile location
#     container_name: container name
#     image: image name
#     environment: 
#       - ENV=${ENV}
#     networks:
#     restart:
#     volumes:
# volumes:
# networks: 
---
version: "3.0"

services:

# 
# mariadb
#
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    restart: always
    volumes:
      - mariadb:/var
    networks:
      - wordpress-mariadb
    environment:
      - HOST_NAME=${HOST_NAME}
      - HOST_IPV4=${HOST_IPV4}
      - HOST_IPV6=${HOST_IPV6}
      - MARIADB_DB=${MARIADB_DB}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_USER=${MARIADB_ROOT_USER}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}

#
# wordpress
# 
  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    restart: always
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - wordpress-mariadb
      - nginx-wordpress
    depends_on:
      - mariadb

#
# nginx
#
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    image: nginx 
    restart: always
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - nginx-wordpress
    depends_on:
      - wordpress
    ports:
      - '443:443'

volumes:
  mariadb:
    driver_opts:
      type: none
      o: bind
      device: ${VOLUMES_DEVICE}/mariadb
  wordpress:
    driver_opts:
      type: none
      o: bind
      device: ${VOLUMES_DEVICE}/wordpress

networks:
  wordpress-mariadb:
  nginx-wordpress:
...
