DELETE FROM  mysql.user WHERE
  User in ('$MARIADB_ROOT_USER', '')
  AND Host NOT IN ('$HOST_NAME', '$HOST_IPV4', '$HOST_IPV6');
DELETE FROM mysql.user WHERE User='' AND Host='localhost';
SET PASSWORD FOR '$MARIADB_ROOT_USER'@'$HOST_NAME' = PASSWORD('$MARIADB_ROOT_PASSWORD');
CREATE DATABASE IF NOT EXISTS $MARIADB_DB;
CREATE USER '$MARIADB_USER'@'%' IDENTIFIED BY '$MARIADB_PASSWORD';
GRANT ALL PRIVILEGES ON $MARIADB_DB.* TO '$MARIADB_USER'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
