name: Github Action
on:
  push:
  pull_request:
    types: [opened, reopened]
jobs:
  Test-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: make re
